### ISSUE TITLE
Make LSDB conda installable 

### ISSUE THREAD

**Issue by nevencaplar** [astronomy-commons/lsdb#105]
See https://github.com/conda-forge/staged-recipes/pull/24833 for lsdb and associated packaged being made conda-installable. This ticket is to capture this work and progress from LSDB side.

**Comment by delucchi-cmu** [comment]
The relevant .git_attributes.txt should be included in the most recent v0.1.0 release

https://github.com/astronomy-commons/lsdb/releases/tag/v0.1.0

**Comment by delucchi-cmu** [comment]
Adding @camposandro , who is going to work on conda compatibility for the `lsst-sphgeom` package.

**Comment by mjuric** [comment]
Done!

https://anaconda.org/conda-forge/lsdb
