### ISSUE TITLE
head() operation to fetch couple of rows from a single partition to preview the data

### ISSUE THREAD

**Issue by nevencaplar** [astronomy-commons/lsdb#106]
Make `head` operation to quickly look at the data avaliable at `lsdb.Catalog` level. 

For instance, if we load `gaia`, at the moment to look at the data one has to do something like `gaia._ddf.head()`. The goal is to make `head` more user-friendly so that we dont have to go via `_ddf` to look at the data.

**Comment by hombit** [comment]
I'm not sure if it is a right goal for the package API.

Dask dataframe's head() would give you a pandas dataframe with few first rows, not a single partition, so if we'd like to make the interface consistent with it (and more predictable for user), Catalog's head should also do the same. So the output wouldn't be a Catalog instance anymore.

If the goal is to display few rows of data it would work. If the goal is, as the title says, is fetching a single partition, I would prefer to "mirror" Dask dataframe's [.partitions](https://dask.pydata.org/en/latest/generated/dask.dataframe.DataFrame.partitions.html#dask.dataframe.DataFrame.partitions), which would allow to slice Catalog over one or few partitions, returning a new Catalog with valid LSDB metadata.

**Comment by nevencaplar** [comment]
I have modified the title to make clear that we want to expose few rows of data, for preview purposes.
