### ISSUE TITLE
Be able to read only some columns, without fetching all of the columns

### ISSUE THREAD

**Issue by nevencaplar** [astronomy-commons/lsdb#109]
Investigate if there is a possibility to be able to read only some columns, without fetching all of the columns. Especially with modern very wide catalogs, user might be interested in only a couple columns. This could decrease memory consumption and speed up loading times.

**Comment by hombit** [comment]
It is actually already possible (thanks to https://github.com/astronomy-commons/lsdb/pull/82) with `read_hopscat(colums=)`, see an example in [this NB](https://github.com/lincc-frameworks/notebooks_lf/blob/main/ztf_axs_with_lsdb_and_tape.ipynb).

**Comment by nevencaplar** [comment]
As pointed out @hombit, this is implemented.
