### ISSUE TITLE
Enable quick view feature for catalogs

### ISSUE THREAD

**Issue by nevencaplar** [astronomy-commons/lsdb#125]
To best of my understanding, the best way to have a quick insight in values contained in a catalog is to do
catalog._ddf.head(1). 
Enable an user to have a quick view without having to invoke hidden methods - presumably by implementing capability to do catalog.head(1) directly.

**Comment by camposandro** [comment]
This issue seems to be a replica of https://github.com/astronomy-commons/lsdb/issues/106. I'm closing it!
