### ISSUE TITLE
Catalog description when viewing it could be improved to avoid confusion

### ISSUE THREAD

**Issue by nevencaplar** [astronomy-commons/lsdb#126]
Catalog print out says ``Dask DataFrame Structure''
<img width="502" alt="Screenshot 2024-01-22 at 3 14 23 PM" src="https://github.com/astronomy-commons/lsdb/assets/12860669/79ab6769-b7fe-4a04-824f-83ac3d3f0a6c">

but at the same time it is not really Dask DataFrame, which leads to confusion with users. @wilsonbb mentioned to me that the text at the top can be changed - I suggest to make it more suggestive, i.e., lsdb Catalog.

**Comment by delucchi-cmu** [comment]
Even worse when you ask for the `_ddf` and get a sad pink warning bar:

![image](https://github.com/astronomy-commons/lsdb/assets/113376043/285e1ab3-8409-41b6-9737-99e96c4f07c2)
