### ISSUE TITLE
Suggest improvements to API names

### ISSUE THREAD

**Issue by nevencaplar** [astronomy-commons/lsdb#129]
Investigate the names and conventions in astronomical software packages; ensure that our names are consistent and as clear as possible. As an example, I find that `.read_hipscat()` is somewhat confusing as ``read'' part implies that something is actually being done, and it not consistent with lazy load paradigm. 

The end result is a set of suggestion to change the name of certain methods. 

Implementation to be described in a separate ticket.

**Comment by camposandro** [comment]
LSDB, unlike other astronomical packages, operates lazily by nature. Less than a handful of methods implicitly run computations for the user (e.g. `head`, `prune_empty_partitions`, `skymap`), so we decided to keep `read_hipscat`'s current naming and provide more disclaimers in the documentation about this behavior. 

The `*_search` catalog methods are coherently named, and follow the astropy / astropy-healpix decision of having the search keyword in the signature. The exception is `box`, which we should rename to `box_search`.

**Comment by camposandro** [comment]
Closed by #345. A diagram of the LSDB pipeline should further clarify the lazy nature of the package #332.
