### ISSUE TITLE
Inconsistent dtype for _hipscat_index (int64 vs uint64)

### ISSUE THREAD

**Issue by wilsonbb** [astronomy-commons/lsdb#145]
In https://github.com/lincc-frameworks/tape/issues/373, I observed in a run of the [Full FG Dwarf Dipper Search notebook](https://github.com/dirac-institute/ZTF_FG_BoyajianSearch/blob/main/analysis/notebooks/paper/Full%20FG%20Dwarf%20Dipper%20Search.ipynb) inconsistent behavior over whether the `_hipscat_index` column has a dtype of `int64` or `uint64`.

Further inspection within the notebook suggests that this can be the result of joining two lsdb catalogs. See the following screenshots:

![image](https://github.com/astronomy-commons/lsdb/assets/22227694/881a108e-747e-46ec-995e-e3729360fa27)

![image](https://github.com/astronomy-commons/lsdb/assets/22227694/e94e7802-6527-4b15-9a85-4286692129ce)

Is this behavior expected? We are joining on columns which are not the hipscat index, but the resulting catalog still uses `_hipscat_index` as its dask dataframe index, and I would expect the dtype to still remain a `uint64`.

**Comment by nevencaplar** [comment]
@wilsonbb Do you think this might be connected to this issue: https://github.com/astronomy-commons/lsdb/issues/27

**Comment by wilsonbb** [comment]
Possibly, but not sure.

I did take a cursory look at the catalog join code and did notice that when generating the meta lsdb seems to set the index name but not the index dtype.

https://github.com/astronomy-commons/lsdb/blob/main/src/lsdb/dask/merge_catalog_functions.py#L189

That may be irrelevant but might be a place where Dask then infers the dtype incorrectly.
