### ISSUE TITLE
Change conda dependency from dask-core to dask

### ISSUE THREAD

**Issue by hombit** [astronomy-commons/lsdb#146]
Currently, our conda distribution requires `dask-core` to be installed (see it [here](https://github.com/conda-forge/lsdb-feedstock/blob/main/recipe/meta.yaml#L25)), which is analogue of `pip install dask`. We've decided that it would be better to use complete installation of Dask as a dependency (see https://github.com/astronomy-commons/lsdb/issues/121, https://github.com/astronomy-commons/lsdb/pull/135, https://github.com/astronomy-commons/lsdb/pull/122). 

I propose to change conda dependency to `dask`, which is an equivalent of `pip install dask[complete]`.

**Comment by mjuric** [comment]
Resolved via https://github.com/conda-forge/lsdb-feedstock/pull/1
