### ISSUE TITLE
Cannot pass "filters" to `read_hipscat`

### ISSUE THREAD

**Issue by hombit** [astronomy-commons/lsdb#163]
Working on #127, I've found that I cannot use `lsdb.read_hipscat(filters=...)` anymore (it worked few version / one month ago). `filters` is an argument of `pd.read_parquet` which it passes to `pyarrow` for applying column filters on fly.

This is an exception I get:
```
TypeError: read_hipscat() got an unexpected keyword argument 'filters'
```

**Comment by camposandro** [comment]
@hombit, we have a unit test that explicitly tests this feature:
https://github.com/astronomy-commons/lsdb/blob/12271382ee6953c32d4422f0e777d05c0d1bd8f0/tests/lsdb/loaders/hipscat/test_read_hipscat.py#L26-L29

Can you please share more information about this?

**Comment by hombit** [comment]
I think I've just forgotten to use `engine='pyarrow'`, thank you!
