### ISSUE TITLE
Profile slowness in loading a catalog

### ISSUE THREAD

**Issue by delucchi-cmu** [astronomy-commons/lsdb#182]
e.g. loading the 300k+ partition ZTF source 

```
import lsdb
ztf_source_path = "https://epyc.astro.washington.edu/~lincc-frameworks/hipscat_surveys/ztf/ztf_source/"
ztf_source = lsdb.read_hipscat(ztf_source_path) # ZTF Source
```

There's a lot of speculation about what the slowest parts *are* and *if* they can be sped up. Let's close the loop on it.

**Comment by nevencaplar** [comment]
I added a super small notebook testing performance when going via HTTP or via direct epyc. Notebook is [here](https://github.com/lincc-frameworks/notebooks_lf/blob/main/Testing_read_hipscat.ipynb).

Shows 40 second for ztf_sources via epyc, 75 when going via HTTP.

**Comment by smcguire-cmu** [comment]
I've profiled this running on epyc, here are the results:
<img width="1911" alt="Screenshot 2024-03-12 at 2 45 23 PM" src="https://github.com/astronomy-commons/lsdb/assets/123987820/c6fb0494-ac9a-41d7-bdbe-4d19f59d6871">


Main culprits seem to be
- reading parquet metadata 16s (We only need this to get column names and dtypes so we should definitely be able to improve here)
- dask from_map 13s (There may be other ways to load the dask df, and the work on pre filtering before loading should help)
- building hipscat tree 10s (This should soon be eliminated)

**Comment by nevencaplar** [comment]
@smcguire-cmu I suggest to repeat this analysis after recent optimizations, and with 40K ZTF source - and then we can close, in my opinion.

**Comment by smcguire-cmu** [comment]
Sure thing, with the recent optimizations here is the updated result. We changed the `_metadata` loading to use `_common_metadata` instead which significantly sped up the reading parquet metadata and the dask `from_map` steps.
![Screenshot 2024-03-12 at 3 07 36 PM](https://github.com/astronomy-commons/lsdb/assets/123987820/88f0b073-400a-4e73-afaf-dbdc5184dba5)

And with the 40k ztf source it only takes 2.7 seconds.
<img width="1903" alt="Screenshot 2024-03-19 at 2 43 15 PM" src="https://github.com/astronomy-commons/lsdb/assets/123987820/5c70a143-7c35-418e-936e-b8e422863337">

With the pixel tree optimizations coming soon with https://github.com/astronomy-commons/hipscat/issues/225, this should be improved again.
