### ISSUE TITLE
Requirements for IVOA demo

### ISSUE THREAD

**Issue by delucchi-cmu** [astronomy-commons/lsdb#191]
- Enumerate expectations and general flow of IVOA demo.
- Identify missing/inadequate/broken features

**Comment by nevencaplar** [comment]
Notebook is developed here: https://colab.research.google.com/drive/1jGja4e-x97wxfdLyAA_XIGLwAd35JUNb?usp=sharing

**Comment by nevencaplar** [comment]
Demo conducted: https://github.com/lincc-frameworks/IVOA_2024_demo/blob/main/LSDB-quickstart-fornax.ipynb
