### ISSUE TITLE
Output of skymap should be a numpy array

### ISSUE THREAD

**Issue by nevencaplar** [astronomy-commons/lsdb#211]
Refactor skymap so that the output is a numpy array that can be used a result in its own right, as well as sent for plotting. For an example of desired functionality, please consult https://github.com/mjuric/incubator/blob/master/lsdb/lsdb-dataframes.ipynb (e.g., cell 13).

**Comment by nevencaplar** [comment]
It might be better to have skymap.histogram or skymap_histogram being a numpy array containing the ``histogram;; and keep the skymap (being a map) a figure.

**Comment by smcguire-cmu** [comment]
closed in #245
