### ISSUE TITLE
Better default order estimation for lsdb.from_dataframe

### ISSUE THREAD

**Issue by nevencaplar** [astronomy-commons/lsdb#213]
lsdb.from_dataframe seems to need quite a bit of guesswork and work on behalf of the user to guess, or to know the proper order of main catalog and margins (e.g., https://github.com/lincc-frameworks/notebooks_lf/blob/main/sprints/2024/03_07/large-catalogs-tutorial.ipynb). This seems like a large amount of work and understanding expected from the user. We want this to be simpler.

My initial proposal is to have a helper function, perhaps to be run under the hood, that calculates the ``best'' order values, given the inputs.

**Comment by AndyTza** [comment]
I wanted to raise this issue again and advocate for a helper function that would enable the user to find the optimum order values/partition size. 

Here, I am hipscating a custom table (N~2000) using the default lowest order/highest order partitioning threshold: 
```python
# Hipsccat VizieR table
hips_object = lsdb.from_dataframe(
    table_df,
    catalog_name="gold",
    catalog_type="object",
    ra_column="RA_ICRS", 
    dec_column="DE_ICRS")
```
which produces a catalog with only 3 partitions that are extremely large:
![image](https://github.com/astronomy-commons/lsdb/assets/22720676/b415eb4b-4d51-45e7-ad7d-fd4421c5db0e). When we try to crossmatch or other operations on this `hips_object` I have noticed a significant slowdown with computations. 

In contrast, changing the `lowest_order` to 5 will create a hipscatted catalog with 700 partitions that looks much better: 
![image](https://github.com/astronomy-commons/lsdb/assets/22720676/9857d0f6-72e0-4679-b3ce-893ab8415187)
and we noticed better performance crossmatching and computing from a table with more partitions. As a user, it was not obvious to me that I needed to change the lowest_order to achieve a smaller partitioning size. 

Is there a general rule of thumb we should be following with lowest/highest order partitioning to row size and sky coverage of a table?

**Comment by nevencaplar** [comment]
With MOCs being added the performance should not be that affected anymore. As such, this is a bit lower priority, but still valuable.

**Comment by delucchi-cmu** [comment]
I think it might still be reasonable to change the (lowest, highest) range from (0, 5) to something like (3, 7). Having a higher value on the upper end will increase the possible resolution of the MOC and improve joining with very-fine catalogs.

**Comment by delucchi-cmu** [comment]
Let's think a little about just being smarter with the default threshold setting. Unless a user specifies a threshold explicitly, let's determine it with a simple equation like:

`input_df.nbytes/len(input_df) * 1024 * 1024`

similar to how we encourage users to estimate their threshold when importing into parquet, but being more automatic about it.
