### ISSUE TITLE
Documentation version in title

### ISSUE THREAD

**Issue by smcguire-cmu** [astronomy-commons/lsdb#260]
Currently, the title in the top left of the documentation includes the version with the DEV tag from installing it when they were built.
<img width="270" alt="Screenshot 2024-04-02 at 1 51 06 PM" src="https://github.com/astronomy-commons/lsdb/assets/123987820/8a6b61cf-59bd-4224-89c3-7e1646b03a08">
This should be changed to either no version tag or a version tag without the dev part.

**Comment by delucchi-cmu** [comment]
I think this is mostly a consequence of pointing folks to the "latest" version of the documentation. If, instead, we use "stable", it's the version from the last tagged release.

See: https://lsdb.readthedocs.io/en/stable/

A search for "en/latest" turns up a BUNCH of references to the latest readthedocs version, in all of our repos.
