### ISSUE TITLE
Add correct crossmatch generation to generating data notebook

### ISSUE THREAD

**Issue by smcguire-cmu** [astronomy-commons/lsdb#261]
For testing crossmatching, we have files that have the brute force crossmatch computed to test against. It would be good to have these generated as part of the generating test data notebook, instead of them now being generated separately.

**Comment by delucchi-cmu** [comment]
Which notebooks in particular?

**Comment by nevencaplar** [comment]
@smcguire-cmu Can you remind us if this issue is still valid?
