### ISSUE TITLE
Simple functions take huge amount of time on few partitions

### ISSUE THREAD

**Issue by nevencaplar** [astronomy-commons/lsdb#266]
**Bug report**

We tried running the following, relatively simple code 
![code_example](https://github.com/astronomy-commons/lsdb/assets/12860669/3c3cf1f3-66f1-411e-98d1-0f0e3f9b2e44)

where Trilegal is a catalog with around 4500 partitions, we run on 96 cores with plenty of memory. The code goes quickly through most of the partitions, but then it has on last handful; these few partitions take more than the bulk of the partitions!  See the figures below showing how long it takes to get through last few of them!

![dashboard](https://github.com/astronomy-commons/lsdb/assets/12860669/ff62d7d2-b6d1-4ca7-a130-f7fde57f63e2)
![dashboard_process](https://github.com/astronomy-commons/lsdb/assets/12860669/315aefdf-d05c-45f0-b117-8aad83e15c3c)

I am also adding a figure that shows that partitions are roughly of the same size, i.e., it doesn't take too long for few of them because they are too big. 
![sizes](https://github.com/astronomy-commons/lsdb/assets/12860669/11152d73-3bbc-4f8a-ad19-3b314d4c22a4)

It is possible that this is a problem with this particular catalog, but I believe that this might be a more general problem. It might not be LSDB problem, but an issue from when we are creating catalog as well (this one was done with hipscat-import).

1. Determine if this problem is reproducible with other catalogs (e.g., GAIA, ZTF)
2. If yes, identify and fix the issue.

**Before submitting**
Please check the following:

- [x] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [x] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [ ] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by nevencaplar** [comment]
@dougbrn Did we have a similar issue appearing in TAPE?  Do you have better insight?

**Comment by dougbrn** [comment]
I'm not 100% sure, things like this tend to be workflow dependent. A guess is that maybe it has something to do with how data is being moved around at the end of the execution, for example it's held in workers and is being transferred back to the main node/worker for the actual return of the result.
