### ISSUE TITLE
Some integer values are transformed into floats

### ISSUE THREAD

**Issue by nevencaplar** [astronomy-commons/lsdb#27]
Imported datasets have floats in columns where I would expect integers. For example, in the Tape Single Pixel, column PLATE_dr16q_constant has values such as 7337.0. This is almost certainly an integer value in the original dataset and should stay as such. As @erykoff on slack pointed out, this might be related to pandas affinity to change values to floats.

**Comment by delucchi-cmu** [comment]
Confirmed that it's an integer value in both the `dr16q_constant catalog`, and in the combined `tape_test` catalog.

```
import pyarrow.parquet as pq

## TAPE Single Pixel data set
hipscat_dir = "/astro/store/epyc/data3/hipscat/catalogs/tape_test/tape_test_obj"
md_file_name = hipscat_dir +"/Norder=5/Dir=0/Npix=4438.parquet"
parquet_file = pq.ParquetFile(md_file_name)
print(parquet_file.schema.to_arrow_schema().field("PLATE_dr16q_constant"))

## dr16q AGN catalog
hipscat_dir="/data3/epyc/data3/hipscat/catalogs/dr16q_constant"
md_file_name = hipscat_dir + "/_metadata"
parquet_file = pq.ParquetFile(md_file_name)
print(parquet_file.schema.to_arrow_schema().field("PLATE"))
```

**Comment by nevencaplar** [comment]
Should be fixed due to better schema handling (https://github.com/astronomy-commons/hipscat/pull/310)
