### ISSUE TITLE
Installing lsdb via pip on s3-supported platform leads to incompatible fsspect

### ISSUE THREAD

**Issue by nevencaplar** [astronomy-commons/lsdb#294]
Running on Fornax, with `!pip install lsdb`

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
s3fs 2023.12.2 requires fsspec==2023.12.2, but you have fsspec 2023.9.2 which is incompatible.`

**Comment by delucchi-cmu** [comment]
fsspec dependency updated in hipscat v0.3.1 (released today).
