### ISSUE TITLE
read_hipscat(search_filter) is confusing

### ISSUE THREAD

**Issue by hombit** [astronomy-commons/lsdb#308]
**Bug report**

It is not clear from the API docs (and there are no RTD docs) that `read_hipscat(search_filter=...)` would not filter the data, but only the partitions. It is also confusing that `Catalog._search` is private, so user is not supposed to reuse the same search object: `lsdb.read_hipscat(search_filter=search).search(search)`.

**Before submitting**
Please check the following:

- [x] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [ ] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [ ] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by nevencaplar** [comment]
I agree. I believe we did this ``coarse'' so that it is faster, but it is very unclear and misleading.

**Comment by delucchi-cmu** [comment]
Sandro - can you write up some alternatives for discussion?

**Comment by camposandro** [comment]
We decided to change the current behavior of `read_hipscat(search_filter)` to meet the users' expectations, performing the fine search in addition to the partition coarse search. We should try to add `fine` as a property of the search object and make the internal [`_search`](https://github.com/astronomy-commons/lsdb/blob/0ab3345ec3ce501d9c892443c6f4f83a3f84c32c/src/lsdb/catalog/catalog.py#L299) method public so users can reuse their search objects if desired.
