### ISSUE TITLE
Documentation: add a high-level diagram of the LSDB pipeline

### ISSUE THREAD

**Issue by hombit** [astronomy-commons/lsdb#332]
It would be useful to show users what LSDB does on different stages of the pipeline: where we read metadata, where we read data and do computations, where we operate on hipscat-level w/o reading the data.

![IMG_4345](https://github.com/astronomy-commons/lsdb/assets/1784493/555edf30-607b-4232-bd82-8151e9ac5001)

**Comment by camposandro** [comment]
Closed by https://github.com/astronomy-commons/lsdb/pull/363.
