### ISSUE TITLE
`read_hipscat` from the url path, have an option to cache the results on the local disc

### ISSUE THREAD

**Issue by nevencaplar** [astronomy-commons/lsdb#340]
When `read_hipscat` from the url path, have an option to cache the results on the local disc. Check if the data is on the local disk and load from local disc (not url) if the data is locally avaliable.

**Comment by delucchi-cmu** [comment]
This can be accomplished by constructing the fsspec using some specific caching arguments. This can be done with the implementation for https://github.com/astronomy-commons/hipscat/issues/307, which will allow passing the constructed fsspec object, instead of simply the `storage_options`.
