### ISSUE TITLE
Documentation: highlight that from_dataframe is not for large datasets

### ISSUE THREAD

**Issue by hombit** [astronomy-commons/lsdb#376]
We should highlight that `from_dataframe()` is not designed for large datasets (>~1M rows) and that `hipscat-import` should be used instead. This should go to both docstring and RTD

**Comment by smcguire-cmu** [comment]
This would also be good as a warning when we run `from_dataframe` to check the size of the input data frame and raise a warning if it's large.

**Comment by camposandro** [comment]
This has been completed by #379.
