### ISSUE TITLE
module 'hipscat.pixel_math' has no attribute 'compute_pixel_map'

### ISSUE THREAD

**Issue by marixko** [astronomy-commons/lsdb#385]
**Bug report**

I am trying to use lsdb.from_dataframe() to crossmatch two dataframes. I am getting "AttributeError: module 'hipscat.pixel_math' has no attribute 'compute_pixel_map'" error message:
![image](https://github.com/user-attachments/assets/1b66b61b-9180-48ca-b408-aa9556143ae7)

I am running lsdb 0.2.7, Python 3.12. 

Code:
```
from astropy.table import Table
import lsdb

legacy = Table.read("sweep-000m005-005p000.fits") # downloaded from https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/south/sweep/10.1/
names = [name for name in legacy.colnames if len(legacy[name].shape) <= 1]
legacy = legacy[names].to_pandas()

lsdb.from_dataframe(legacy, ra_column="RA", dec_column="DEC", margin_threshold=3600)
```

**Before submitting**
Please check the following:

- [x] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [x] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [ ] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by hombit** [comment]
@marixko thank you for the report! Just in case, could you please check if you have up-to-date `hipscat` and `lsdb`? Could you please run
```sh
pip uninstall lsdb hipscat
pip install lsdb
```

**Comment by delucchi-cmu** [comment]
Sorry! This is my bad. I've just tagged lsdb v0.2.8 that contains the fix. This should propagate to pypi within the hour.

**Comment by marixko** [comment]
It is working flawlessly now, thank you! :smile:
