### ISSUE TITLE
Change html representation to reflect laziness of catalog

### ISSUE THREAD

**Issue by delucchi-cmu** [astronomy-commons/lsdb#387]
**Feature request**

In the `_repr_html` method, let's figure out how to make clear that the catalog's data has not been loaded. This may be in removing the dataframe, or indicating that this is a dummy dataframe only.

e.g. in https://github.com/astronomy-commons/lsdb/blob/main/src/lsdb/catalog/dataset/dataset.py#L32

**Before submitting**
Please check the following:

- [ ] I have described the purpose of the suggested change, specifying what I need the enhancement to accomplish, i.e. what problem it solves.
- [ ] I have included any relevant links, screenshots, environment information, and data relevant to implementing the requested feature, as well as pseudocode for how I want to access the new functionality.
- [ ] If I have ideas for how the new feature could be implemented, I have provided explanations and/or pseudocode and/or task lists for the steps.

**Comment by nevencaplar** [comment]
Superseeded by #399
