### ISSUE TITLE
Restructure documentation

### ISSUE THREAD

**Issue by smcguire-cmu** [astronomy-commons/lsdb#398]
The current documentation structure can be somewhat confusing to new users trying to get started with the project. Restructuring the layout of the documentation would help with this.

**Comment by delucchi-cmu** [comment]
Please please add more detail.

**Comment by smcguire-cmu** [comment]
We discussed this in the weekly meeting on 2024-08-13, and the decision for the layout we decided upon was:


- root
  - home
  - installation/getting started
  - tutorials (landing page can give some divisions / narrative)
    - Loading data into LSDB
      - // reads from data.lsdb.io
      - // lazy diagram	 (remove it from the Tutorials page)
      - // skyplot
      - // schema
    - Working with large catalogs rename to "Filtering large catalogs"
    - <todo - cross match and join>
    - Export
    - Topic: Importing your own data
    - Topic: Margins
    - Science use case: …

This was implemented in #406
