### ISSUE TITLE
Improve Lazy Loaded Catalog Representation

### ISSUE THREAD

**Issue by smcguire-cmu** [astronomy-commons/lsdb#399]
Currently the catalog representation copies the dask data frame lazy representation, which confuses users to thinking the data has been loaded, especially with the hipscat id column. Some other way of showing the table would be useful, and replacing the index column to show the HEALPix pixels instead of the hipscat id might be a good start for this.

**Comment by delucchi-cmu** [comment]
Is this different from: https://github.com/astronomy-commons/lsdb/issues/387 ?

**Comment by nevencaplar** [comment]
No, it is the same problem. I think we have decided to start first with removing  hipscat id column values, and then evaluating based on the feedback if this is sufficient change.

**Comment by smcguire-cmu** [comment]
Closed in #514
