### ISSUE TITLE
Return empty margin catalog instead of None with from_dataframe

### ISSUE THREAD

**Issue by hombit** [astronomy-commons/lsdb#419]
**Bug report**

`from_dataframe()` should assign empty margin catalog instead of `None` when margin is empty. Originated from this discussion:
https://github.com/astronomy-commons/lsdb/issues/416#issuecomment-2359150932

It looks like it is the similar to #329

**Before submitting**
Please check the following:

- [x] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [x] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [ ] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by hombit** [comment]
A reproducible example

```python
import pandas as pd
from lsdb import from_dataframe

# Fails
assert from_dataframe(pd.DataFrame({'ra': [1.0], 'dec': [1.0]})).margin is not None
```

**Comment by camposandro** [comment]
Issue closed by https://github.com/astronomy-commons/lsdb/pull/508.
