### ISSUE TITLE
Make reduce output a catalog

### ISSUE THREAD

**Issue by hombit** [astronomy-commons/lsdb#420]
**Feature request**

It would be really nice if `Catalog.reduce()` would return a catalog object, so it can be spatially-joined or dumped to the disk. Also it would be great, if we can make it assign new columns back to the original catalog (or its copy), because it is a very popular use-case.

**Before submitting**
Please check the following:

- [x] I have described the purpose of the suggested change, specifying what I need the enhancement to accomplish, i.e. what problem it solves.
- [ ] I have included any relevant links, screenshots, environment information, and data relevant to implementing the requested feature, as well as pseudocode for how I want to access the new functionality.
- [ ] If I have ideas for how the new feature could be implemented, I have provided explanations and/or pseudocode and/or task lists for the steps.

**Comment by dougbrn** [comment]
@smcguire-cmu https://github.com/astronomy-commons/lsdb/pull/414
