### ISSUE TITLE
Add Catalog.nest_lists method

### ISSUE THREAD

**Issue by hombit** [astronomy-commons/lsdb#421]
**Feature request**

Some Hats catalogs are expected to have list-arrays which we'd like to pack into a nested column. `nested-dask` has `NestedFrame.from_lists` for that, I propose to wrap it in LSDB and provide a new `Catalog.nest_lists()` method for that. I have a prototype I made for the Alerce alerts data (see [this NB](https://github.com/lincc-frameworks/notebooks_lf/blob/main/alerce_sample-SN_search_Epyc.ipynb))

```python
def pack_lists(
        catalog: Catalog,
        base_columns: list[str] | None,
        list_columns: list[str] | None = None,
        name: str = 'nested',
):
    """Pack list-columns into nested columns
    
    Margin cache support is not implemented
    """
    new_ddf = NestedFrame.from_lists(
        catalog._ddf,
        base_columns=base_columns,
        list_columns=list_columns,
        name=name,
    )
    return Catalog(new_ddf, catalog._ddf_pixel_map, catalog.hc_structure)
```

**Before submitting**
Please check the following:

- [x] I have described the purpose of the suggested change, specifying what I need the enhancement to accomplish, i.e. what problem it solves.
- [x] I have included any relevant links, screenshots, environment information, and data relevant to implementing the requested feature, as well as pseudocode for how I want to access the new functionality.
- [x] If I have ideas for how the new feature could be implemented, I have provided explanations and/or pseudocode and/or task lists for the steps.

**Comment by dougbrn** [comment]
This should be resolved by #431 , feel free to reopen if not the case
