### ISSUE TITLE
MOCs are lost when performing join/crossmatch

### ISSUE THREAD

**Issue by smcguire-cmu** [astronomy-commons/lsdb#428]
Currently crossmatching/joining loses MOC info, since the aligned MOC isn't returned by the hipscat alignment functions. So after crossmatching or joining, the benefits of the MOCs are lost.

I think the best way to fix this is to include a `moc` attribute in the `PixelAlignment` class, and use that in the crossmatch/join catalog methods.

**Comment by camposandro** [comment]
This was closed by #438.
