### ISSUE TITLE
ENH: s3fs as dependency

### ISSUE THREAD

**Issue by bsipocz** [astronomy-commons/lsdb#436]
s3fs is an optional dependency for hipscat so it's not installed for end users when they install lsdb. It would be nice to have an extras here that pulls in the corresponding extras of hipscat.

**Comment by hombit** [comment]
I believe we shouldn't add an extra per each protocol (think about others: FTP, SSHFS, etc). I'd propose to either make a better error message when one of the fsspec's dependency is missed (https://github.com/astronomy-commons/hipscat/issues/313), or just add s3fs to the list of default dependencies.

**Comment by bsipocz** [comment]
What about  including `hipscat[dev]` in the dev extras here? But of course having an explicit fsspec in hipscat would solve it, too.

The error message way I don't think is ideal as the end user is a few packages down the chain so these implied dependencies would be nice to be treated well (e.g they never directly call s3fs, so it shouldn't really be in their explicit requirements file but via something they use)

**Comment by hombit** [comment]
+1 to add it to the `dev` extras!

I believe the error message can be fixed, `fsspec` actually raises an exception with a good message - we just overwrite it for some reason. See https://github.com/astronomy-commons/hipscat/issues/313 for details

**Comment by delucchi-cmu** [comment]
We weren't using the s3fs or adlfs dependencies in hats (formerly hipscat), and they have been removed from there as well.

However, with changes from https://github.com/astronomy-commons/hats/pull/336, we no longer override the fsspec error message, and trying to load an S3 resource without `s3fs` gives the error: `ImportError: Install s3fs to access S3`, which is more intelligible to users.

Do you think this resolves some of your frustrations? I'm hesitant to add (even optional) dependencies for protocols that aren't used explicitly in any hats code.

**Comment by bsipocz** [comment]
I see the hesitation, however our end code doesn't use it either so when I apply the same logic it gets me the error. So I would think adding an extras that adds the extras for fsspec, which by default is just too slim cut, would be a good solution.

**Comment by delucchi-cmu** [comment]
With #476, you get all of the fsspec implementations (in addition to a few jupyter nice-to-haves) with: `python -m pip install lsdb[full]`
