### ISSUE TITLE
Nested behavior with duplicate indices

### ISSUE THREAD

**Issue by camposandro** [astronomy-commons/lsdb#455]
**Bug report**

When a catalog has duplicate `_healpix_29` indices the nested functionality does not work as expected. The `test_nest_lists` unit test was failing because of this and we temporarily assigned unique ids to fix it:

```python
cat_ndf = small_sky_with_nested_sources._ddf.map_partitions(
  lambda df: df.set_index(df.index.to_numpy() + np.arange(len(df)))
)
```

**Before submitting**
Please check the following:

- [X] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [X] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [X] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by nevencaplar** [comment]
see https://github.com/lincc-frameworks/nested-pandas/issues/161
