### ISSUE TITLE
Import SDSS DR18

### ISSUE THREAD

**Issue by camposandro** [astronomy-commons/lsdb#459]
Import the SDSS DR18 _SpecPhotoAll_, which is a precomputed join between the _PhotoObjAll_ and _SpecObjAll_ tables. Its schema can be found in https://skyserver.sdss.org/dr18/MoreTools/browser.

**Comment by nevencaplar** [comment]
In progress, currently waiting for J. Hopkins to provide this catalog. Expected in ~5 to 10 days.

**Comment by camposandro** [comment]
This catalog was imported, validated and published on [data.lsdb.io](https://data.lsdb.io).
