### ISSUE TITLE
plot_pixels show colorbar values for the values which are not present on the plot

### ISSUE THREAD

**Issue by nevencaplar** [astronomy-commons/lsdb#467]
For instance, colorbar shows order 5 even thought it is not present on the plot

![Screenshot 2024-10-25 at 2 53 44 PM](https://github.com/user-attachments/assets/77052d57-990d-4de2-9262-35b41d83be0f)

**Comment by smcguire-cmu** [comment]
Can you post the code that made this plot?

**Comment by nevencaplar** [comment]
I am unable to reproduce. I will reopen with an example if it appears.
