### ISSUE TITLE
Nest/unnest sources for cross-matching

### ISSUE THREAD

**Issue by delucchi-cmu** [astronomy-commons/lsdb#52]
Try out a strategy to include lightcurves in joins by including as additional columns on the object table.

protocol
- catalog a + source catalog -> catalog a with source catalog as nested arrays
- same for catalog b
- cross-match catalogs a and b
- boom - the lightcurves are already on the cross match result in those nested array fields

**Comment by smcguire-cmu** [comment]
Closing this as #367 covers this issue
