### ISSUE TITLE
Handling _hipscat_index column if it is not a pandas index

### ISSUE THREAD

**Issue by hombit** [astronomy-commons/lsdb#67]
I noticed that LSDB sometimes make an assumption about `_hipscat_index` to be `pd.DataFrame`'s index. It is not always true: my hipscat-imported SFD catalog is loaded with `_hipscat_index` to be a regular column, not an index. 

Is `_hipscat_index` being a pandas index a part of the HiPSCat standard? Should we make it a part of it? Or should we just manually check it and set index with LSDB?

**Comment by delucchi-cmu** [comment]
I'm inclined to say that: no - the IVOA standard should likely not say anything about available pandas metadata in the parquet files. If the `_hipscat_index` field is available, we should use it as the pandas index and use for dask divisions.
