### ISSUE TITLE
for_each function for mapping over light curves

### ISSUE THREAD

**Issue by smcguire-cmu** [astronomy-commons/lsdb#83]
The foreach method should perform a groupby apply on a column such as the object id, but do it within mapping the partitions instead of performing a shuffle.

This is currently implemented in the `ADASS_TUTORIAL` branch, but has an error with empty partitions where the groupby apply is not applied, and so the data frame is not transformed and there is a dask meta error.

**Comment by nevencaplar** [comment]
Closed, not valid anymore due to #367
