### ISSUE TITLE
Catalog loading may spend a lot of time on to_pyarrow_string

### ISSUE THREAD

**Issue by hombit** [astronomy-commons/lsdb#89]
When loading HiPSCat catalogs (for example PS1 DR2 OTMO), I noticed that LSDB spends up to ~50% of time on `to_pyarrow_string()`.

I think that the issue could be because current pipeline is like the following:
- Loading individual parquet file with pandas, using the default `numpy` dtype backend, here we convert `pyarrow` strings to `numpy`
- After we put it to Dask, and it converts strings back to `pyarrow`

**Comment by hombit** [comment]
`read_hipscat(dtype_backend='pyarrow')` helps a lot. However I don't see an easy option to have all columns but string to be `numpy`.

See [this benchmark NB](https://github.com/lincc-frameworks/notebooks_lf/blob/d59a27d7c6a6df1ae0932ac51247c1e85e654f35/read-str-columns-with-lsdb.ipynb)

**Comment by erykoff** [comment]
There is no easy way, that is true.  But pandas string handling is truly terrible, and going through that is definitely going to be a bottleneck.  (numpy string handling is terrible in a different way, and python string handling is terrible in yet a different way of course).

This was what I wrote for going parquet through arrow to numpy/astropy: https://github.com/astropy/astropy/blob/main/astropy/io/misc/parquet.py .  It has served me well, but I haven't actually checked how much the special casing of the strings slows it down.

**Comment by hombit** [comment]
@erykoff thank you! I believe that here we have one more layer of the problem, Dask. It is Dask who converts string Series to `string[pyarrow]`. So I believe we have back and forth conversion happening in our pipeline: from parquet to numpy with `pd.read_parquet` and from numpy to arrow implicitly with Dask.

Personally I would prefer to slowly move to `pyarrow` dtypes since pandas v2 got some support of them.
